In [6]:
import numpy as np
import pandas as pd

In [112]:
hanoi = pd.read_csv('results/hanoi.csv')
blocks = pd.read_csv('results/blocks.csv')
skgrid = pd.read_csv('results/skgrid.csv')

In [116]:
blocks

,problem,obs,metric,socres,real_goal,pred_goal,correct,correct_num
0,output/blocks_gr/,0.1,MaxUtil,"[-0.06399997877307731, -4.7384112114222176e-07...",0,0,True,1
1,output/blocks_gr/,0.1,DP,"[-1, 0, 0, 0]",0,0,True,1
2,output/blocks_gr/,0.1,KL,"[0.2136591812174647, 2.941088740884222, nan, 3...",0,0,True,1
3,output/blocks_gr/,0.1,KL2,"[0.21358579533378672, 2.940919962761799, 5.128...",0,0,True,1
4,output/blocks_gr/,0.3,MaxUtil,"[-0.18969587367235008, -0.00010162636839846296...",0,2,False,0
...,...,...,...,...,...,...,...,...
195,output/blocks_gr10/,0.7,KL2,"[0.3072463564248778, 1.7596190310932247, 10.29...",0,0,True,1
196,output/blocks_gr10/,1.0,MaxUtil,"[-1.6655743999999957, -0.0037185119305866007, ...",0,0,True,1
197,output/blocks_gr10/,1.0,DP,"[-8, 0, 0, 0]",0,0,True,1
198,output/blocks_gr10/,1.0,KL,"[0.41944461557484336, 1.7493278426311765, 8.22...",0,0,True,1
199,output/blocks_gr10/,1.0,KL2,"[0.4193536392387379, 1.7491903348307924, 8.224...",0,0,True,1

In [114]:
blocks.groupby(['obs', 'metric']).sum()

             real_goal  pred_goal  correct  correct_num
obs metric
0.1 DP               0          5        7            7
    KL               0          2        9            9
    KL2              0          6        7            7
    MaxUtil          0          3        8            8
0.3 DP               0          2        9            9
    KL               0          3        9            9
    KL2              0          3        9            9
    MaxUtil          0          4        8            8
0.5 DP               0          3        8            8
    KL               0          5        7            7
    KL2              0          5        7            7
    MaxUtil          0          4        8            8
0.7 DP               0          2        9            9
    KL               0          0       10           10
    KL2              0          0       10           10
    MaxUtil          0          2        9            9
1.0 DP               0          2        9            9
    KL               0          0       10           10
    KL2              0          0       10           10
    MaxUtil          0          4        8            8

In [115]:
blocks.groupby(['metric', 'obs']).sum()

             real_goal  pred_goal  correct  correct_num
metric  obs
DP      0.1          0          5        7            7
        0.3          0          2        9            9
        0.5          0          3        8            8
        0.7          0          2        9            9
        1.0          0          2        9            9
KL      0.1          0          2        9            9
        0.3          0          3        9            9
        0.5          0          5        7            7
        0.7          0          0       10           10
        1.0          0          0       10           10
KL2     0.1          0          6        7            7
        0.3          0          3        9            9
        0.5          0          5        7            7
        0.7          0          0       10           10
        1.0          0          0       10           10
MaxUtil 0.1          0          3        8            8
        0.3          0          4        8            8
        0.5          0          4        8            8
        0.7          0          2        9            9
        1.0          0          4        8            8

In [43]:
hanoi

,problem,obs,metric,g0,g1,g2,g3,real_goal,pred_goal,correct
0,output/hanoi_gr/,0.1,MaxUtil,-0.025600,-0.057680,-0.001638,-0.025600,0,1,0
1,output/hanoi_gr/,0.1,DP,-1.000000,0.000000,0.000000,-1.000000,0,3,0
2,output/hanoi_gr/,0.1,KL,0.641546,3.165443,2.170193,0.641546,0,3,0
3,output/hanoi_gr/,0.1,KL2,0.641451,3.165273,2.170051,0.641451,0,3,0
4,output/hanoi_gr/,0.3,MaxUtil,-1.224000,-0.013806,-0.004458,-0.624000,0,0,1
...,...,...,...,...,...,...,...,...,...,...
195,output/hanoi_gr10/,0.7,KL2,0.534316,6.355919,3.145348,0.534316,0,3,0
196,output/hanoi_gr10/,1.0,MaxUtil,-1.666639,-0.226869,-0.000007,-0.106665,0,0,1
197,output/hanoi_gr10/,1.0,DP,-12.000000,0.000000,0.000000,-12.000000,0,3,0
198,output/hanoi_gr10/,1.0,KL,0.508032,5.758177,3.035946,0.508032,0,3,0
199,output/hanoi_gr10/,1.0,KL2,0.507919,5.757848,3.035728,0.507919,0,3,0

In [44]:
hanoi.groupby(['obs', 'metric']).sum()

                     g0         g1         g2         g3  real_goal  \
obs metric
0.1 DP       -15.000000  -3.000000  -3.000000  -3.000000          0
    KL         5.933438  42.437334  20.867746  70.179852          0
    KL2        5.932381  31.795894  19.775045  48.115979          0
    MaxUtil   -3.880877  -0.091479  -0.432698  -0.463140          0
0.3 DP       -37.000000  -7.000000  -8.000000 -12.000000          0
    KL         5.405983  37.670989  70.001193  38.483970          0
    KL2        5.404960  29.064245  53.851273  32.008369          0
    MaxUtil   -7.642862  -1.242701  -1.050725  -2.062335          0
0.5 DP       -56.000000 -12.000000 -13.000000 -17.000000          0
    KL         5.306183  33.841958  41.217231  38.313889          0
    KL2        5.305164  28.142198  37.761388  35.368721          0
    MaxUtil   -9.519377  -1.194691  -1.133064  -2.154923          0
0.7 DP       -77.000000 -13.000000 -17.000000 -22.000000          0
    KL         5.270673  33.973377  52.151260  42.349605          0
    KL2        5.269645  25.522808  40.235564  36.146719          0
    MaxUtil  -12.893116  -2.351971  -1.293150  -1.794493          0
1.0 DP      -104.000000 -19.000000 -24.000000 -31.000000          0
    KL         5.248544  34.479601  45.602246  44.058562          0
    KL2        5.247524  27.101940  35.929835  38.332084          0
    MaxUtil  -16.634546  -2.951800  -1.859070  -3.229075          0

             pred_goal  correct
obs metric
0.1 DP              10        5
    KL               5        7
    KL2              8        5
    MaxUtil          7        6
0.3 DP               9        6
    KL               6        8
    KL2              6        8
    MaxUtil          7        7
0.5 DP               5        7
    KL               0       10
    KL2              3        9
    MaxUtil          4        8
0.7 DP               7        7
    KL               6        8
    KL2              6        8
    MaxUtil          4        8
1.0 DP               4        8
    KL               3        9
    KL2              3        9
    MaxUtil          1        9

In [23]:
skgrid

,problem,metric,g0,g1,g2,g3,real_goal,pred_goal,correct
0,output/skgrid_gr/,MaxUtil,-1.666434,-0.276057,-0.022196,-0.003451,0,0,1
1,output/skgrid_gr/,DP,-12.000000,-3.000000,-2.000000,0.000000,0,0,1
2,output/skgrid_gr/,KL,0.851187,2.532397,2.634207,3.199733,0,0,1
3,output/skgrid_gr/,KL2,0.851141,2.532345,2.634156,3.199680,0,0,1
4,output/skgrid_gr2/,MaxUtil,-1.666230,-0.106458,-0.670389,-0.144768,0,0,1
5,output/skgrid_gr2/,DP,-9.000000,-9.000000,-2.000000,-6.000000,0,1,0
6,output/skgrid_gr2/,KL,0.716731,1.123880,1.370453,2.012458,0,0,1
7,output/skgrid_gr2/,KL2,0.716683,1.123831,1.370403,2.012405,0,0,1
8,output/skgrid_gr3/,MaxUtil,-1.659839,-0.004049,-0.002517,-0.129466,0,0,1
9,output/skgrid_gr3/,DP,-6.000000,0.000000,0.000000,-3.000000,0,0,1
10,output/skgrid_gr3/,KL,0.807086,3.025022,5.373499,2.476472,0,0,1
11,output/skgrid_gr3/,KL2,0.807037,3.024965,5.373433,2.476417,0,0,1
12,output/skgrid_gr4/,MaxUtil,-1.664994,-0.773462,-0.159067,-1.753930,0,3,0
13,output/skgrid_gr4/,DP,-12.000000,-5.000000,-4.000000,-10.000000,0,0,1
14,output/skgrid_gr4/,KL,0.752046,1.472148,2.550390,1.066584,0,0,1
15,output/skgrid_gr4/,KL2,0.752008,1.472107,2.550345,1.144327,0,0,1
16,output/skgrid_gr5/,MaxUtil,-1.663936,-0.264566,-0.313773,-0.263543,0,0,1
17,output/skgrid_gr5/,DP,-7.000000,0.000000,0.000000,-1.000000,0,0,1
18,output/skgrid_gr5/,KL,0.619936,1.563015,2.464116,3.676438,0,0,1
19,output/skgrid_gr5/,KL2,0.619885,1.562959,2.464057,3.676375,0,0,1
20,output/skgrid_gr6/,MaxUtil,-1.666667,-0.890814,-1.666597,-0.823719,0,0,1
21,output/skgrid_gr6/,DP,-18.000000,0.000000,-11.000000,-4.000000,0,0,1
22,output/skgrid_gr6/,KL,0.486588,5.187412,0.659975,3.937657,0,0,1
23,output/skgrid_gr6/,KL2,0.486554,3.458236,1.181045,3.718853,0,0,1
24,output/skgrid_gr7/,MaxUtil,-1.666593,-0.874879,-0.002731,-0.729598,0,0,1
25,output/skgrid_gr7/,DP,-11.000000,0.000000,-11.000000,-4.000000,0,2,0
26,output/skgrid_gr7/,KL,0.659784,3.144248,0.659906,1.538271,0,0,1
27,output/skgrid_gr7/,KL2,0.659742,3.144197,0.659864,1.538225,0,0,1
28,output/skgrid_gr8/,MaxUtil,-1.666667,-1.666666,-0.874749,-1.666666,0,0,1
29,output/skgrid_gr8/,DP,-24.000000,-17.000000,-9.000000,-16.000000,0,0,1
30,output/skgrid_gr8/,KL,0.318175,0.360245,2.346113,0.357727,0,0,1
31,output/skgrid_gr8/,KL2,0.318148,0.838468,1.661805,0.905111,0,0,1
32,output/skgrid_gr9/,MaxUtil,-1.666662,-1.666597,-1.494142,-1.666492,0,0,1
33,output/skgrid_gr9/,DP,-14.000000,-11.000000,-2.000000,-10.000000,0,0,1
34,output/skgrid_gr9/,KL,0.426991,0.468099,6.619748,0.474855,0,0,1
35,output/skgrid_gr9/,KL2,0.426954,0.796318,3.738401,0.624855,0,0,1
36,output/skgrid_gr10/,MaxUtil,-1.666597,-0.106662,-1.524414,-1.666492,0,0,1
37,output/skgrid_gr10/,DP,-11.000000,-11.000000,-2.000000,-10.000000,0,1,0
38,output/skgrid_gr10/,KL,0.468099,0.468099,5.691261,0.474855,0,0,1
39,output/skgrid_gr10/,KL2,0.468059,0.468059,3.286106,0.613462,0,0,1

In [45]:
skgrid.groupby(['obs', 'metric']).sum()

                     g0         g1         g2         g3  real_goal  \
obs metric
0.1 DP       -18.000000 -12.000000 -10.000000  -9.000000          0
    KL         5.864269  13.960047  23.650634  23.000620          0
    KL2        5.863860  14.554905  26.078745  19.706245          0
    MaxUtil   -2.993234  -0.761513  -1.493391  -0.474109          0
0.3 DP       -43.000000 -31.000000 -25.000000 -20.000000          0
    KL         5.812074  17.787339  28.742224  16.728098          0
    KL2        5.811642  18.546594  21.198211  18.425270          0
    MaxUtil   -6.100530  -3.610280  -2.329518  -2.088834          0
0.5 DP       -64.000000 -42.000000 -33.000000 -42.000000          0
    KL         5.776460  18.041437  26.853942  18.530560          0
    KL2        5.776061  16.964693  24.131102  18.826320          0
    MaxUtil   -8.859569  -2.324269  -4.728624  -5.235773          0
0.7 DP       -91.000000 -45.000000 -40.000000 -51.000000          0
    KL         5.868020  18.902696  30.665820  19.356497          0
    KL2        5.867603  18.032798  25.926371  19.860840          0
    MaxUtil  -11.121306  -4.750466  -4.374670  -5.752608          0
1.0 DP      -124.000000 -56.000000 -43.000000 -64.000000          0
    KL         6.106622  19.344565  30.369669  19.215049          0
    KL2        6.106210  18.421485  24.919615  19.909710          0
    MaxUtil  -16.654617  -6.630212  -6.730574  -8.848125          0

             pred_goal  correct
obs metric
0.1 DP              17        3
    KL               4        7
    KL2              7        5
    MaxUtil          6        6
0.3 DP              10        4
    KL               5        8
    KL2              2        9
    MaxUtil          4        7
0.5 DP              11        4
    KL               6        7
    KL2              3        8
    MaxUtil         12        5
0.7 DP               8        6
    KL               5        8
    KL2              5        8
    MaxUtil          8        7
1.0 DP               4        7
    KL               0       10
    KL2              0       10
    MaxUtil          3        9

In [25]:
blocks.groupby('metric').sum()

,g0,g1,g2,g3,real_goal,pred_goal,correct
metric,,,,,,,
DP,-80.000000,-5.000000,-24.000000,-4.000000,0,2,9
KL,5.832681,47.023265,35.328307,61.755960,0,0,10
KL2,5.831464,39.281756,35.423613,51.550202,0,0,10
MaxUtil,-16.624475,-0.281371,-5.324660,-0.226488,0,4,8

In [35]:
hanoi.groupby('metric').sum()

,g0,g1,g2,g3,real_goal,pred_goal,correct
metric,,,,,,,
DP,-104.000000,-19.000000,-24.000000,-31.000000,0,4,8
KL,5.248544,34.479601,45.602246,44.058562,0,3,9
KL2,5.247524,27.101940,35.929835,38.332084,0,3,9
MaxUtil,-16.634546,-2.951800,-1.859070,-3.229075,0,1,9

In [27]:
skgrid.groupby('metric').sum()

,g0,g1,g2,g3,real_goal,pred_goal,correct
metric,,,,,,,
DP,-124.000000,-56.000000,-43.000000,-64.000000,0,4,7
KL,6.106622,19.344565,30.369669,19.215049,0,0,10
KL2,6.106210,18.421485,24.919615,19.909710,0,0,10
MaxUtil,-16.654617,-6.630212,-6.730574,-8.848125,0,3,9

In [56]:
hanoi[hanoi.metric == 'KL']

,problem,obs,metric,g0,g1,g2,g3,real_goal,pred_goal,correct
2,output/hanoi_gr/,0.1,KL,0.641546,3.165443,2.170193,0.641546,0,3,0
6,output/hanoi_gr/,0.3,KL,0.561210,7.454279,2.241892,1.001853,0,0,1
10,output/hanoi_gr/,0.5,KL,0.482012,5.700500,2.119987,0.812494,0,0,1
14,output/hanoi_gr/,0.7,KL,0.496941,4.529959,2.223179,0.496941,0,3,0
18,output/hanoi_gr/,1.0,KL,0.515954,5.425414,2.175649,0.704801,0,0,1
22,output/hanoi_gr2/,0.1,KL,0.641546,0.641546,3.403313,5.707230,0,1,0
26,output/hanoi_gr2/,0.3,KL,0.509170,0.509170,4.895696,6.652934,0,0,1
30,output/hanoi_gr2/,0.5,KL,0.482012,0.482012,4.451502,6.464430,0,0,1
34,output/hanoi_gr2/,0.7,KL,0.545143,0.545143,5.783808,10.777793,0,0,1
38,output/hanoi_gr2/,1.0,KL,0.515954,0.515954,5.093495,8.344503,0,0,1
42,output/hanoi_gr3/,0.1,KL,0.641546,2.169925,3.044394,3.044394,0,0,1
46,output/hanoi_gr3/,0.3,KL,0.521042,2.170044,3.164898,3.164898,0,0,1
50,output/hanoi_gr3/,0.5,KL,0.561210,2.219132,3.342385,3.194410,0,0,1
54,output/hanoi_gr3/,0.7,KL,0.581294,2.206831,3.267887,3.156906,0,0,1
58,output/hanoi_gr3/,1.0,KL,0.545143,2.211431,3.290010,3.196838,0,0,1
62,output/hanoi_gr4/,0.1,KL,0.400538,2.247385,3.322285,3.295902,0,0,1
66,output/hanoi_gr4/,0.3,KL,0.521042,2.345471,4.429612,4.224993,0,0,1
70,output/hanoi_gr4/,0.5,KL,0.480874,2.317532,4.068953,3.569459,0,0,1
74,output/hanoi_gr4/,0.7,KL,0.496941,2.274773,4.126196,3.774226,0,0,1
78,output/hanoi_gr4/,1.0,KL,0.521042,2.302244,4.018409,3.700459,0,0,1
82,output/hanoi_gr5/,0.1,KL,0.641546,2.934554,2.202106,3.835456,0,0,1
86,output/hanoi_gr5/,0.3,KL,0.710363,3.071394,2.932132,3.206592,0,0,1
90,output/hanoi_gr5/,0.5,KL,0.632907,3.124896,3.020450,3.226295,0,0,1
94,output/hanoi_gr5/,0.7,KL,0.538231,3.036312,2.585273,3.624265,0,0,1
98,output/hanoi_gr5/,1.0,KL,0.567750,3.050192,2.668338,3.528101,0,0,1
102,output/hanoi_gr6/,0.1,KL,0.521042,NaN,1.299548,8.885242,0,0,1
106,output/hanoi_gr6/,0.3,KL,0.496941,3.572972,0.671525,3.350869,0,0,1
110,output/hanoi_gr6/,0.5,KL,0.501527,2.790184,0.696154,6.041776,0,0,1
114,output/hanoi_gr6/,0.7,KL,0.517804,4.345996,0.717336,7.350110,0,0,1
118,output/hanoi_gr6/,1.0,KL,0.518668,3.989957,0.768792,6.143697,0,0,1
122,output/hanoi_gr7/,0.1,KL,0.641546,NaN,NaN,2.014902,0,0,1
126,output/hanoi_gr7/,0.3,KL,0.513919,1.996585,19.956490,0.513919,0,3,0
130,output/hanoi_gr7/,0.5,KL,0.521042,4.576796,16.720584,0.699140,0,0,1
134,output/hanoi_gr7/,0.7,KL,0.510087,4.429935,15.259072,0.838247,0,0,1
138,output/hanoi_gr7/,1.0,KL,0.518668,3.903377,11.544486,0.759318,0,0,1
142,output/hanoi_gr8/,0.1,KL,0.521042,0.521042,2.182653,6.876196,0,1,0
146,output/hanoi_gr8/,0.3,KL,0.545143,0.809528,26.911901,7.330210,0,0,1
150,output/hanoi_gr8/,0.5,KL,0.531653,0.531653,2.181829,9.964320,0,0,1
154,output/hanoi_gr8/,0.7,KL,0.517804,0.815910,14.211844,6.618221,0,0,1
158,output/hanoi_gr8/,1.0,KL,0.518667,0.737278,12.269116,9.209533,0,0,1
162,output/hanoi_gr9/,0.1,KL,0.641541,21.279302,0.740630,35.237438,0,0,1
166,output/hanoi_gr9/,0.3,KL,0.545141,8.772207,0.849162,8.555690,0,0,1
170,output/hanoi_gr9/,0.5,KL,0.591904,3.846594,0.781917,3.820524,0,0,1
174,output/hanoi_gr9/,0.7,KL,0.531996,5.432245,0.831093,5.178465,0,0,1
178,output/hanoi_gr9/,1.0,KL,0.518667,6.585576,0.738005,7.963279,0,0,1
182,output/hanoi_gr10/,0.1,KL,0.641546,9.478137,2.502625,0.641546,0,0,1
186,output/hanoi_gr10/,0.3,KL,0.482012,6.969339,3.947884,0.482012,0,3,0
190,output/hanoi_gr10/,0.5,KL,0.521042,8.252658,3.833471,0.521042,0,0,1
194,output/hanoi_gr10/,0.7,KL,0.534431,6.356274,3.145573,0.534431,0,3,0
198,output/hanoi_gr10/,1.0,KL,0.508032,5.758177,3.035946,0.508032,0,3,0

In [48]:
blocks[blocks.obs == 1.0].groupby('metric').sum()

,obs,g0,g1,g2,g3,real_goal,pred_goal,correct
metric,,,,,,,,
DP,10.0,-80.000000,-5.000000,-24.000000,-4.000000,0,2,9
KL,10.0,5.832681,47.023265,35.328307,61.755960,0,0,10
KL2,10.0,5.831464,39.281756,35.423613,51.550202,0,0,10
MaxUtil,10.0,-16.624475,-0.281371,-5.324660,-0.226488,0,4,8

In [54]:
skgrid.groupby('metric').count()

         problem  obs  g0  g1  g2  g3  real_goal  pred_goal  correct
metric
DP            50   50  50  50  50  50         50         50       50
KL            50   50  50  49  49  50         50         50       50
KL2           50   50  50  50  50  50         50         50       50
MaxUtil       50   50  50  50  50  50         50         50       50

In [55]:
blocks[blocks.metric == 'KL'].groupby('obs').count()

     problem  metric  g0  g1  g2  g3  real_goal  pred_goal  correct
obs
0.1       10      10  10   9   8   9         10         10       10
0.3       10      10  10  10  10  10         10         10       10
0.5       10      10  10  10  10  10         10         10       10
0.7       10      10  10  10  10  10         10         10       10
1.0       10      10  10  10  10  10         10         10       10

In [ ]:
blocks.groupby('metric').count()

In [ ]:
def accuracy(df):
    for o in df.obs.unique():

In [ ]:
obs metric accuracy precision recall fscore

In [59]:
from sklearn.metrics import confusion_matrix

In [73]:
confusion_matrix(
    blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].real_goal, blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].pred_goal
)

array([[9, 1],
       [0, 0]])

In [94]:
M = confusion_matrix(
    blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].real_goal, blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].pred_goal
)
tn, fp, fn, tp = M.ravel()

In [105]:
total = blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].correct.count()

In [95]:
M

array([[9, 1],
       [0, 0]])

In [100]:
print(tn, fp, fn, tp)

9 1 0 0

In [106]:
recall = tp / total 
accuracy = tn + tp / total   
precision = tp / (tp + fp)

In [107]:
accuracy

9.0

In [108]:
precision

0.0

In [109]:
recall

0.0

In [78]:
import pandas as pd
from pandas_ml import ConfusionMatrix

Confusion_Matrix = ConfusionMatrix(
    blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].real_goal, blocks[(blocks.obs == 0.3) & (blocks.metric == 'KL')].pred_goal)
Confusion_Matrix.print_stats()

AttributeError: module 'sklearn.preprocessing' has no attribute 'Imputer'

In [69]:
blocks[(blocks.obs == 1.0) & (blocks.metric == 'KL')].pred_goal

18     0
38     0
58     0
78     0
98     0
118    0
138    0
158    0
178    0
198    0
Name: pred_goal, dtype: int64

In [58]:
for o in blocks.obs.unique():
    print(o)

0.1
0.3
0.5
0.7
1.0

In [5]:
data1.groupby('metric').sum()

,g0,g1,g2,g3,real_goal,pred_goal,correct
metric,,,,,,,
DP,-104.000000,-19.000000,-24.000000,-31.000000,0,4,8
KL,5.248544,34.787960,49.656908,42.657136,0,4,8
KL2,5.247524,26.904768,38.950701,37.130897,0,4,8
MaxUtil,-16.634546,-2.949038,-1.866892,-3.234970,0,1,9

In [190]:
data1 = pd.read_csv('test_files/nav/problem4/results.csv')
data1

   start  goal  pred_goal   metric
0    0.0   0.0        0.0  MaxUtil
1    0.0   1.0        1.0  MaxUtil
2    0.0   0.0        0.0       KL
3    0.0   1.0        1.0       KL
4    0.0   0.0        0.0       DP
5    0.0   1.0        1.0       DP

In [191]:
MaxUtil_metric = data1[data1.metric == 'MaxUtil']
KL_metric = data1[data1.metric == 'KL']
DP_metric = data1[data1.metric == 'DP']

In [192]:
def conf_matrix(df):
    confusion_matrix = pd.crosstab(df.goal, df.pred_goal, rownames=['Actual'], colnames=['Predicted'])
    return confusion_matrix

In [193]:
conf_matrix(MaxUtil_metric)

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [194]:
conf_matrix(KL_metric)

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [195]:
conf_matrix(DP_metric)

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [2]:
def conf_matrix(df):
    confusion_matrix = pd.crosstab(df.goal, df.pred_goal, rownames=['Actual'], colnames=['Predicted'])
    return confusion_matrix

In [3]:
def display_matrix(df):
    for i in df.step.unique():
        df_temp = df[df.step == i]
        print(f'step: {i}')
        display(conf_matrix(df_temp))

In [4]:
data = pd.read_csv('test_files/nav/problem4/results2.csv')
data

    start  goal  pred_goal   metric  step
0     0.0   0.0        0.0  MaxUtil   1.0
1     0.0   0.0        0.0  MaxUtil   2.0
2     0.0   0.0        0.0  MaxUtil   3.0
3     0.0   0.0        0.0  MaxUtil  full
4     0.0   1.0        1.0  MaxUtil   1.0
5     0.0   1.0        1.0  MaxUtil   2.0
6     0.0   1.0        1.0  MaxUtil   3.0
7     0.0   1.0        1.0  MaxUtil  full
8     0.0   0.0        0.0       KL   1.0
9     0.0   0.0        0.0       KL   2.0
10    0.0   0.0        0.0       KL   3.0
11    0.0   0.0        0.0       KL  full
12    0.0   1.0        1.0       KL   1.0
13    0.0   1.0        1.0       KL   2.0
14    0.0   1.0        1.0       KL   3.0
15    0.0   1.0        1.0       KL  full
16    0.0   0.0        1.0       DP   1.0
17    0.0   0.0        0.0       DP   2.0
18    0.0   0.0        0.0       DP   3.0
19    0.0   0.0        0.0       DP  full
20    0.0   1.0        1.0       DP   1.0
21    0.0   1.0        1.0       DP   2.0
22    0.0   1.0        1.0       DP   3.0
23    0.0   1.0        1.0       DP  full

In [5]:
full_data = data[data.step == 'full']

In [6]:
MaxUtil_metric = data[data.metric == 'MaxUtil']
KL_metric = data[data.metric == 'KL']
DP_metric = data[data.metric == 'DP']

In [7]:
conf_matrix(full_data[full_data.metric == 'MaxUtil'])

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [8]:
conf_matrix(full_data[full_data.metric == 'MaxUtil'])

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [9]:
conf_matrix(full_data[full_data.metric == 'DP'])

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [237]:
conf_matrix(full_data[full_data.metric == 'KL'])

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [11]:
import hvplot.pandas

In [19]:
prueba = data.copy()
prueba['acierto'] = 0
prueba.loc[prueba.goal == prueba.pred_goal, 'acierto'] = 1

In [21]:
prueba[prueba.metric == 'MaxUtil']

   start  goal  pred_goal   metric  step  acierto
0    0.0   0.0        0.0  MaxUtil   1.0        1
1    0.0   0.0        0.0  MaxUtil   2.0        1
2    0.0   0.0        0.0  MaxUtil   3.0        1
3    0.0   0.0        0.0  MaxUtil  full        1
4    0.0   1.0        1.0  MaxUtil   1.0        1
5    0.0   1.0        1.0  MaxUtil   2.0        1
6    0.0   1.0        1.0  MaxUtil   3.0        1
7    0.0   1.0        1.0  MaxUtil  full        1

In [23]:
prueba[prueba.metric == 'DP'].groupby('step').sum()

      start  goal  pred_goal  acierto
step
1.0     0.0   1.0        2.0        1
2.0     0.0   1.0        1.0        2
3.0     0.0   1.0        1.0        2
full    0.0   1.0        1.0        2

In [28]:
prueba[prueba.metric == 'DP'].groupby('step').sum()['acierto'].hvplot()

:Curve   [step]   (acierto)

In [17]:
data[data.metric == 'MaxUtil'].groupby('step').sum()

      start  goal  pred_goal
step
1.0     0.0   1.0        1.0
2.0     0.0   1.0        1.0
3.0     0.0   1.0        1.0
full    0.0   1.0        1.0

In [13]:
data.hvplot()

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [234]:
display_matrix(MaxUtil_metric)

step: 1.0

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

step: 2.0

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

step: 3.0

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

step: full

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

Predicted  0.0  1.0
Actual
0.0          1    0
1.0          0    1

In [196]:
pd.crosstab(KL_metric.goal, KL_metric.pred_goal, margins=True)

pred_goal  0.0  1.0  All
goal
0.0          1    0    1
1.0          0    1    1
All          1    1    2